name: SpeedBall
main: need.speedball.SpeedBall
version: 0.4.1
commands:
   sbgame:
    description:
    usage:
     /<command> <subcmd>
   sbselect:
    description: 
    usage:
     /<command> <subcmd>
   sbplay:
    description: 
    usage:
     /<command> <subcmd>
   sblist:
    description:
    usage:
     /<command> <subcmd>
   sbpers:
    description:
    usage:
     /<command> <subcmd>
   sbremove:
    description:
    usage:
     /<command> <subcmd>